# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arpit Babbar
email: me@arpitbabbar.dev
description: >- # this means to ignore newlines until "baseurl:"
  My academic website as a researcher of numerical algorithms for PDE solvers. Applications of my research include fluid dynamics. The particular numerical algorithms that I study are high-order, discontinuous Galerkin finite element methods.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

author:
  name   : "Arpit Babbar"
  avatar : "/assets/bio_pixel.png"
  bio    : "Math grad approximating the approximations of physics"
  links:
    - label: "TIFR-CAM"
      icon: "fas fa-fw fa-map-marker"
      url: "https://www.math.tifrbng.res.in/people/arpit"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:arpit@babbar.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arpit-babbar"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-9453-370X"
    - label: "Research Gate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Arpit_Babbar"

# Build settings
markdown: kramdown
remote_theme: "Arpit-Babbar/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
#
#
# Source - https://github.com/mmistakes/minimal-mistakes/issues/1740#issuecomment-503997931
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages #posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: # true
      # share: true
      # related: true
  # _pages
  - scope:
      path: "_news"
      type: pages
    values:
      layout: single
      author_profile: true
